# http server configs
api:
  port: 5050
  debug: false

# service bootstrap configs (reading the initial logs)
bootstrap:
  enable: true
  logs_path: "logs/dumb"
  batch_size: 500

# database configs (SQLite3)
database:
  path: "data.db"

# logging configs
logging:
  level: "debug"
